# Generated by Django 4.0.1 on 2022-09-14 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('f_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('f_name', models.CharField(max_length=60)),
                ('f_procedure', models.TextField()),
                ('f_photo', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ing', models.CharField(max_length=60)),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bezen_app.food')),
            ],
        ),
    ]
