# Generated by Django 4.0.1 on 2022-09-17 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bezen_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='ingredients',
            field=models.TextField(default='na'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='food',
            name='f_description',
            field=models.CharField(max_length=200, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='food',
            name='f_name',
            field=models.CharField(max_length=60, verbose_name='Item name'),
        ),
        migrations.AlterField(
            model_name='food',
            name='f_photo',
            field=models.ImageField(blank=True, null=True, upload_to='food_img', verbose_name='Item Photo'),
        ),
        migrations.AlterField(
            model_name='food',
            name='f_procedure',
            field=models.TextField(verbose_name='procedure'),
        ),
        migrations.DeleteModel(
            name='Ingredient',
        ),
    ]
